// https://developers.google.com/custom-search/docs/json_api_reference
const LANGUAGES = {
  "af": "Afrikaans",
  "ak": "Akan",
  "sq": "Albanian",
  "ws": "Samoa",
  "am": "Amharic",
  "ar": "Arabic",
  "hy": "Armenian",
  "az": "Azerbaijani",
  "eu": "Basque",
  "be": "Belarusian",
  "bem": "Bemba",
  "bn": "Bengali",
  "bh": "Bihari",
  "bs": "Bosnian",
  "br": "Breton",
  "bg": "Bulgarian",
  "bt": "Bhutanese",
  "km": "Cambodian",
  "ca": "Catalan",
  "chr": "Cherokee",
  "ny": "Chichewa",
  "zh-cn": "Chinese (Simplified)",
  "zh-tw": "Chinese (Traditional)",
  "co": "Corsican",
  "hr": "Croatian",
  "cs": "Czech",
  "da": "Danish",
  "nl": "Dutch",
  "en": "English",
  "eo": "Esperanto",
  "et": "Estonian",
  "ee": "Ewe",
  "fo": "Faroese",
  "tl": "Filipino",
  "fi": "Finnish",
  "fr": "French",
  "fy": "Frisian",
  "gaa": "Ga",
  "gl": "Galician",
  "ka": "Georgian",
  "de": "German",
  "el": "Greek",
  "kl": "Greenlandic",
  "gn": "Guarani",
  "gu": "Gujarati",
  "ht": "Haitian Creole",
  "ha": "Hausa",
  "haw": "Hawaiian",
  "iw": "Hebrew",
  "he": "Hebrew",
  "hi": "Hindi",
  "hu": "Hungarian",
  "is": "Icelandic",
  "ig": "Igbo",
  "id": "Indonesian",
  "ia": "Interlingua",
  "ga": "Irish",
  "it": "Italian",
  "ja": "Japanese",
  "jw": "Javanese",
  "kn": "Kannada",
  "kk": "Kazakh",
  "rw": "Kinyarwanda",
  "rn": "Kirundi",
  "kg": "Kongo",
  "ko": "Korean",
  "kri": "Krio (Sierra Leone)",
  "ku": "Kurdish",
  "ckb": "Kurdish (Soranî)",
  "ky": "Kyrgyz",
  "lo": "Laothian",
  "la": "Latin",
  "lv": "Latvian",
  "ln": "Lingala",
  "lt": "Lithuanian",
  "loz": "Lozi",
  "lg": "Luganda",
  "ach": "Luo",
  "mk": "Macedonian",
  "mg": "Malagasy",
  "ms": "Malay",
  "ml": "Malayalam",
  "mt": "Maltese",
  "mv": "Maldives",
  "mi": "Maori",
  "mr": "Marathi",
  "mfe": "Mauritian Creole",
  "mo": "Moldavian",
  "mn": "Mongolian",
  "sr-me": "Montenegrin",
  "my": "Myanmar",
  "ne": "Nepali",
  "pcm": "Nigerian Pidgin",
  "nso": "Northern Sotho",
  "no": "Norwegian",
  "nn": "Norwegian (Nynorsk)",
  "oc": "Occitan",
  "or": "Oriya",
  "om": "Oromo",
  "ps": "Pashto",
  "fa": "Persian",
  "pl": "Polish",
  "pt": "Portuguese",
  "pt-br": "Portuguese (Brazil)",
  "pt-pt": "Portuguese (Portugal)",
  "pa": "Punjabi",
  "qu": "Quechua",
  "ro": "Romanian",
  "rm": "Romansh",
  "nyn": "Runyakitara",
  "ru": "Russian",
  "gd": "Scots Gaelic",
  "sr": "Serbian",
  "sh": "Serbo-Croatian",
  "st": "Sesotho",
  "tn": "Setswana",
  "crs": "Seychellois Creole",
  "sn": "Shona",
  "sd": "Sindhi",
  "si": "Sinhalese",
  "sk": "Slovak",
  "sl": "Slovenian",
  "so": "Somali",
  "es": "Spanish",
  "es-419": "Spanish (Latin American)",
  "su": "Sundanese",
  "sw": "Swahili",
  "sv": "Swedish",
  "tg": "Tajik",
  "ta": "Tamil",
  "tt": "Tatar",
  "te": "Telugu",
  "th": "Thai",
  "ti": "Tigrinya",
  "to": "Tonga",
  "lua": "Tshiluba",
  "tum": "Tumbuka",
  "tr": "Turkish",
  "tk": "Turkmen",
  "tw": "Twi",
  "ug": "Uighur",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "uz": "Uzbek",
  "vu": "Vanuatu",
  "vi": "Vietnamese",
  "cy": "Welsh",
  "wo": "Wolof",
  "xh": "Xhosa",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "zu": "Zulu"
};

const COUNTRIES = {
  "af": "Afghanistan",
  "al": "Albania",
  "dz": "Algeria",
  "as": "American Samoa",
  "ad": "Andorra",
  "ao": "Angola",
  "ai": "Anguilla",
  "aq": "Antarctica",
  "ag": "Antigua and Barbuda",
  "ar": "Argentina",
  "am": "Armenia",
  "aw": "Aruba",
  "au": "Australia",
  "at": "Austria",
  "az": "Azerbaijan",
  "bs": "Bahamas",
  "bh": "Bahrain",
  "bd": "Bangladesh",
  "bb": "Barbados",
  "by": "Belarus",
  "be": "Belgium",
  "bz": "Belize",
  "bj": "Benin",
  "bm": "Bermuda",
  "bt": "Bhutan",
  "bo": "Bolivia",
  "ba": "Bosnia and Herzegovina",
  "bw": "Botswana",
  "bv": "Bouvet Island",
  "br": "Brazil",
  "io": "British Indian Ocean Territory",
  "bn": "Brunei Darussalam",
  "bg": "Bulgaria",
  "bf": "Burkina Faso",
  "bi": "Burundi",
  "kh": "Cambodia",
  "cm": "Cameroon",
  "ca": "Canada",
  "cv": "Cape Verde",
  "ky": "Cayman Islands",
  "cf": "Central African Republic",
  "td": "Chad",
  "cl": "Chile",
  "cn": "China",
  "cx": "Christmas Island",
  "cc": "Cocos (Keeling) Islands",
  "co": "Colombia",
  "km": "Comoros",
  "cg": "Congo",
  "cd": "Congo, the Democratic Republic of the",
  "ck": "Cook Islands",
  "cr": "Costa Rica",
  "ci": "Cote D'ivoire",
  "hr": "Croatia",
  "cu": "Cuba",
  "cy": "Cyprus",
  "cz": "Czech Republic",
  "dk": "Denmark",
  "dj": "Djibouti",
  "dm": "Dominica",
  "do": "Dominican Republic",
  "ec": "Ecuador",
  "eg": "Egypt",
  "sv": "El Salvador",
  "gq": "Equatorial Guinea",
  "er": "Eritrea",
  "ee": "Estonia",
  "et": "Ethiopia",
  "fk": "Falkland Islands (Malvinas)",
  "fo": "Faroe Islands",
  "fj": "Fiji",
  "fi": "Finland",
  "fr": "France",
  "gf": "French Guiana",
  "pf": "French Polynesia",
  "tf": "French Southern Territories",
  "ga": "Gabon",
  "gm": "Gambia",
  "ge": "Georgia",
  "de": "Germany",
  "gh": "Ghana",
  "gi": "Gibraltar",
  "gr": "Greece",
  "gl": "Greenland",
  "gd": "Grenada",
  "gp": "Guadeloupe",
  "gu": "Guam",
  "gt": "Guatemala",
  "gg": "Guernsey",
  "gn": "Guinea",
  "gw": "Guinea-Bissau",
  "gy": "Guyana",
  "ht": "Haiti",
  "hm": "Heard Island and Mcdonald Islands",
  "va": "Holy See (Vatican City State)",
  "hn": "Honduras",
  "hk": "Hong Kong",
  "hu": "Hungary",
  "is": "Iceland",
  "in": "India",
  "id": "Indonesia",
  "ir": "Iran, Islamic Republic of",
  "iq": "Iraq",
  "ie": "Ireland",
  "im": "Isle of Man",
  "il": "Israel",
  "it": "Italy",
  "je": "Jersey",
  "jm": "Jamaica",
  "jp": "Japan",
  "jo": "Jordan",
  "kz": "Kazakhstan",
  "ke": "Kenya",
  "ki": "Kiribati",
  "kp": "Korea, Democratic People's Republic of",
  "kr": "Korea, Republic of",
  "kw": "Kuwait",
  "kg": "Kyrgyzstan",
  "la": "Lao People's Democratic Republic",
  "lv": "Latvia",
  "lb": "Lebanon",
  "ls": "Lesotho",
  "lr": "Liberia",
  "ly": "Libyan Arab Jamahiriya",
  "li": "Liechtenstein",
  "lt": "Lithuania",
  "lu": "Luxembourg",
  "mo": "Macao",
  "mk": "Macedonia, the Former Yugosalv Republic of",
  "mg": "Madagascar",
  "mw": "Malawi",
  "my": "Malaysia",
  "mv": "Maldives",
  "ml": "Mali",
  "mt": "Malta",
  "mh": "Marshall Islands",
  "mq": "Martinique",
  "mr": "Mauritania",
  "mu": "Mauritius",
  "yt": "Mayotte",
  "mx": "Mexico",
  "fm": "Micronesia, Federated States of",
  "md": "Moldova, Republic of",
  "mc": "Monaco",
  "mn": "Mongolia",
  "me": "Montenegro",
  "ms": "Montserrat",
  "ma": "Morocco",
  "mz": "Mozambique",
  "mm": "Myanmar",
  "na": "Namibia",
  "nr": "Nauru",
  "np": "Nepal",
  "nl": "Netherlands",
  "an": "Netherlands Antilles",
  "nc": "New Caledonia",
  "nz": "New Zealand",
  "ni": "Nicaragua",
  "ne": "Niger",
  "ng": "Nigeria",
  "nu": "Niue",
  "nf": "Norfolk Island",
  "mp": "Northern Mariana Islands",
  "no": "Norway",
  "om": "Oman",
  "pk": "Pakistan",
  "pw": "Palau",
  "ps": "Palestinian Territory, Occupied",
  "pa": "Panama",
  "pg": "Papua New Guinea",
  "py": "Paraguay",
  "pe": "Peru",
  "ph": "Philippines",
  "pn": "Pitcairn",
  "pl": "Poland",
  "pt": "Portugal",
  "pr": "Puerto Rico",
  "qa": "Qatar",
  "re": "Reunion",
  "ro": "Romania",
  "ru": "Russian Federation",
  "rw": "Rwanda",
  "sh": "Saint Helena",
  "kn": "Saint Kitts and Nevis",
  "lc": "Saint Lucia",
  "pm": "Saint Pierre and Miquelon",
  "vc": "Saint Vincent and the Grenadines",
  "ws": "Samoa",
  "sm": "San Marino",
  "st": "Sao Tome and Principe",
  "sa": "Saudi Arabia",
  "sn": "Senegal",
  "rs": "Serbia",
  "sc": "Seychelles",
  "sl": "Sierra Leone",
  "sg": "Singapore",
  "sk": "Slovakia",
  "si": "Slovenia",
  "sb": "Solomon Islands",
  "so": "Somalia",
  "za": "South Africa",
  "gs": "South Georgia and the South Sandwich Islands",
  "es": "Spain",
  "lk": "Sri Lanka",
  "sd": "Sudan",
  "sr": "Suriname",
  "sj": "Svalbard and Jan Mayen",
  "sz": "Swaziland",
  "se": "Sweden",
  "ch": "Switzerland",
  "sy": "Syrian Arab Republic",
  "tw": "Taiwan, Province of China",
  "tj": "Tajikistan",
  "tz": "Tanzania, United Republic of",
  "th": "Thailand",
  "tl": "Timor-Leste",
  "tg": "Togo",
  "tk": "Tokelau",
  "to": "Tonga",
  "tt": "Trinidad and Tobago",
  "tn": "Tunisia",
  "tr": "Turkiye",
  "tm": "Turkmenistan",
  "tc": "Turks and Caicos Islands",
  "tv": "Tuvalu",
  "ug": "Uganda",
  "ua": "Ukraine",
  "ae": "United Arab Emirates",
  "uk": "United Kingdom",
  "gb": "United Kingdom",
  "us": "United States",
  "um": "United States Minor Outlying Islands",
  "uy": "Uruguay",
  "uz": "Uzbekistan",
  "vu": "Vanuatu",
  "ve": "Venezuela",
  "vn": "Viet Nam",
  "vg": "Virgin Islands, British",
  "vi": "Virgin Islands, U.S.",
  "wf": "Wallis and Futuna",
  "eh": "Western Sahara",
  "ye": "Yemen",
  "zm": "Zambia",
  "zw": "Zimbabwe"
};

const LR_LANGUAGES = {
  "lang_ar": "Arabic",
  "lang_hy": "Armenian",
  "lang_bg": "Bulgarian",
  "lang_ca": "Catalan",
  "lang_zh-CN": "Chinese (Simplified)",
  "lang_zh-TW": "Chinese (Traditional)",
  "lang_hr": "Croatian",
  "lang_cs": "Czech",
  "lang_da": "Danish",
  "lang_nl": "Dutch",
  "lang_en": "English",
  "lang_et": "Estonian",
  "lang_tl": "Filipino",
  "lang_fi": "Finnish",
  "lang_fr": "French",
  "lang_de": "German",
  "lang_el": "Greek",
  "lang_iw": "Hebrew",
  "lang_he": "Hebrew",
  "lang_hi": "Hindi",
  "lang_hu": "Hungarian",
  "lang_is": "Icelandic",
  "lang_id": "Indonesian",
  "lang_it": "Italian",
  "lang_ja": "Japanese",
  "lang_ko": "Korean",
  "lang_lv": "Latvian",
  "lang_lt": "Lithuanian",
  "lang_no": "Norwegian",
  "lang_fa": "Persian",
  "lang_pl": "Polish",
  "lang_pt": "Portuguese",
  "lang_ro": "Romanian",
  "lang_ru": "Russian",
  "lang_sr": "Serbian",
  "lang_sk": "Slovak",
  "lang_sl": "Slovenian",
  "lang_es": "Spanish",
  "lang_sv": "Swedish",
  "lang_th": "Thai",
  "lang_tr": "Turkish",
  "lang_uk": "Ukrainian",
  "lang_vi": "Vietnamese"
};

const CR_COUNTRIES = {
  "countryAF": "Afghanistan",
  "countryAL": "Albania",
  "countryDZ": "Algeria",
  "countryAS": "American Samoa",
  "countryAD": "Andorra",
  "countryAO": "Angola",
  "countryAI": "Anguilla",
  "countryAQ": "Antarctica",
  "countryAG": "Antigua and Barbuda",
  "countryAR": "Argentina",
  "countryAM": "Armenia",
  "countryAW": "Aruba",
  "countryAU": "Australia",
  "countryAT": "Austria",
  "countryAZ": "Azerbaijan",
  "countryBS": "Bahamas",
  "countryBH": "Bahrain",
  "countryBD": "Bangladesh",
  "countryBB": "Barbados",
  "countryBY": "Belarus",
  "countryBE": "Belgium",
  "countryBZ": "Belize",
  "countryBJ": "Benin",
  "countryBM": "Bermuda",
  "countryBT": "Bhutan",
  "countryBO": "Bolivia",
  "countryBA": "Bosnia and Herzegovina",
  "countryBW": "Botswana",
  "countryBV": "Bouvet Island",
  "countryBR": "Brazil",
  "countryIO": "British Indian Ocean Territory",
  "countryVG": "British Virgin Islands",
  "countryBN": "Brunei",
  "countryBG": "Bulgaria",
  "countryBF": "Burkina Faso",
  "countryBI": "Burundi",
  "countryKH": "Cambodia",
  "countryCM": "Cameroon",
  "countryCA": "Canada",
  "countryCV": "Cape Verde",
  "countryKY": "Cayman Islands",
  "countryCF": "Central African Republic",
  "countryTD": "Chad",
  "countryCL": "Chile",
  "countryCN": "China",
  "countryCX": "Christmas Island",
  "countryCC": "Cocos (Keeling) Islands",
  "countryCO": "Colombia",
  "countryKM": "Comoros",
  "countryCG": "Congo",
  "countryCD": "Congo, the Democratic Republic of the",
  "countryCK": "Cook Islands",
  "countryCR": "Costa Rica",
  "countryCI": "Cote D'ivoire",
  "countryHR": "Croatia",
  "countryCU": "Cuba",
  "countryCY": "Cyprus",
  "countryCZ": "Czechia",
  "countryDK": "Denmark",
  "countryDJ": "Djibouti",
  "countryDM": "Dominica",
  "countryDO": "Dominican Republic",
  "countryTP": "East Timor",
  "countryEC": "Ecuador",
  "countryEG": "Egypt",
  "countrySV": "El Salvador",
  "countryGQ": "Equatorial Guinea",
  "countryER": "Eritrea",
  "countryEE": "Estonia",
  "countryET": "Ethiopia",
  "countryEU": "European Union",
  "countryFK": "Falkland Islands (Malvinas)",
  "countryFO": "Faroe Islands",
  "countryFJ": "Fiji",
  "countryFI": "Finland",
  "countryFR": "France",
  "countryFX": "France, Metropolitan",
  "countryGF": "French Guiana",
  "countryPF": "French Polynesia",
  "countryTF": "French Southern Territories",
  "countryGA": "Gabon",
  "countryGM": "Gambia",
  "countryGE": "Georgia",
  "countryDE": "Germany",
  "countryGH": "Ghana",
  "countryGI": "Gibraltar",
  "countryGR": "Greece",
  "countryGL": "Greenland",
  "countryGD": "Grenada",
  "countryGP": "Guadeloupe",
  "countryGU": "Guam",
  "countryGT": "Guatemala",
  "countryGN": "Guinea",
  "countryGW": "Guinea-Bissau",
  "countryGY": "Guyana",
  "countryHT": "Haiti",
  "countryHM": "Heard Island and Mcdonald Islands",
  "countryHN": "Honduras",
  "countryHK": "Hong Kong",
  "countryHU": "Hungary",
  "countryIS": "Iceland",
  "countryIN": "India",
  "countryID": "Indonesia",
  "countryIR": "Iran",
  "countryIQ": "Iraq",
  "countryIE": "Ireland",
  "countryIL": "Israel",
  "countryIT": "Italy",
  "countryJM": "Jamaica",
  "countryJP": "Japan",
  "countryJO": "Jordan",
  "countryKZ": "Kazakhstan",
  "countryKE": "Kenya",
  "countryKI": "Kiribati",
  "countryKP": "Korea, Democratic People's Republic of",
  "countryKR": "Korea, Republic of",
  "countryKW": "Kuwait",
  "countryKG": "Kyrgyzstan",
  "countryLA": "Laos",
  "countryLV": "Latvia",
  "countryLB": "Lebanon",
  "countryLS": "Lesotho",
  "countryLR": "Liberia",
  "countryLY": "Libya",
  "countryLI": "Liechtenstein",
  "countryLT": "Lithuania",
  "countryLU": "Luxembourg",
  "countryMO": "Macao",
  "countryMK": "Macedonia, the Former Yugosalv Republic of",
  "countryMG": "Madagascar",
  "countryMW": "Malawi",
  "countryMY": "Malaysia",
  "countryMV": "Maldives",
  "countryML": "Mali",
  "countryMT": "Malta",
  "countryMH": "Marshall Islands",
  "countryMQ": "Martinique",
  "countryMR": "Mauritania",
  "countryMU": "Mauritius",
  "countryYT": "Mayotte",
  "countryMX": "Mexico",
  "countryFM": "Micronesia",
  "countryMD": "Moldova",
  "countryMC": "Monaco",
  "countryMN": "Mongolia",
  "countryMS": "Montserrat",
  "countryMA": "Morocco",
  "countryMZ": "Mozambique",
  "countryMM": "Myanmar (Burma)",
  "countryNA": "Namibia",
  "countryNR": "Nauru",
  "countryNP": "Nepal",
  "countryNL": "Netherlands",
  "countryAN": "Netherlands Antilles",
  "countryNC": "New Caledonia",
  "countryNZ": "New Zealand",
  "countryNI": "Nicaragua",
  "countryNE": "Niger",
  "countryNG": "Nigeria",
  "countryNU": "Niue",
  "countryNF": "Norfolk Island",
  "countryMP": "Northern Mariana Islands",
  "countryNO": "Norway",
  "countryOM": "Oman",
  "countryPK": "Pakistan",
  "countryPW": "Palau",
  "countryPS": "Palestine",
  "countryPA": "Panama",
  "countryPG": "Papua New Guinea",
  "countryPY": "Paraguay",
  "countryPE": "Peru",
  "countryPH": "Philippines",
  "countryPN": "Pitcairn Islands",
  "countryPL": "Poland",
  "countryPT": "Portugal",
  "countryPR": "Puerto Rico",
  "countryQA": "Qatar",
  "countryRE": "Réunion",
  "countryRO": "Romania",
  "countryRU": "Russia",
  "countryRW": "Rwanda",
  "countryWS": "Samoa",
  "countrySM": "San Marino",
  "countryST": "Sao Tome and Principe",
  "countrySA": "Saudi Arabia",
  "countrySN": "Senegal",
  "countryRS": "Serbia",
  "countryCS": "Serbia and Montenegro",
  "countrySC": "Seychelles",
  "countrySL": "Sierra Leone",
  "countrySG": "Singapore",
  "countrySK": "Slovakia",
  "countrySI": "Slovenia",
  "countrySB": "Solomon Islands",
  "countrySO": "Somalia",
  "countryZA": "South Africa",
  "countryGS": "South Georgia and the South Sandwich Islands",
  "countryES": "Spain",
  "countryLK": "Sri Lanka",
  "countrySH": "St. Helena",
  "countryKN": "Saint Kitts and Nevis",
  "countryLC": "Saint Lucia",
  "countryPM": "Saint Pierre and Miquelon",
  "countryVC": "Saint Vincent and Grenadines",
  "countrySD": "Sudan",
  "countrySR": "Suriname",
  "countrySJ": "Svalbard and Jan Mayen",
  "countrySZ": "Swaziland",
  "countrySE": "Sweden",
  "countryCH": "Switzerland",
  "countrySY": "Syria",
  "countryTW": "Taiwan, Province of China",
  "countryTJ": "Tajikistan",
  "countryTZ": "Tanzania, United Republic of",
  "countryTH": "Thailand",
  "countryTG": "Togo",
  "countryTK": "Tokelau",
  "countryTO": "Tonga",
  "countryTT": "Trinidad and Tobago",
  "countryTN": "Tunisia",
  "countryTR": "Turkey",
  "countryTM": "Turkmenistan",
  "countryTC": "Turks and Caicos Islands",
  "countryTV": "Tuvalu",
  "countryUM": "U.S. Outlying Islands",
  "countryVI": "U.S. Virgin Islands",
  "countryUG": "Uganda",
  "countryUA": "Ukraine",
  "countryAE": "United Arab Emirates",
  "countryUK": "United Kingdom",
  "countryGB": "United Kingdom",
  "countryUS": "United States",
  "countryUY": "Uruguay",
  "countryUZ": "Uzbekistan",
  "countryVU": "Vanuatu",
  "countryVA": "Vatican City",
  "countryVE": "Venezuela",
  "countryVN": "Vietnam",
  "countryWF": "Wallis and Futuna",
  "countryEH": "Western Sahara",
  "countryYE": "Yemen",
  "countryYU": "Yugoslavia",
  "countryZM": "Zambia",
  "countryZW": "Zimbabwe"
};

const DEFAULT_FAVORITES = {
  hl: ['en'],
  gl: ['us'],
  lr: ['lang_en'],
  cr: ['countryUS']
};

const DEFAULT_PRESETS = {
  'english-us': {
    name: 'English (US)',
    params: {
      hl: 'en',
      gl: 'us',
      lr: '',
      cr: ''
    }
  }
};
